<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Debug - 1.0.6.2 or Earlier;Debug - 1.0.6.3 or Later;Debug - 1.0.7;Release - 1.0.6.2 or Earlier;Release - 1.0.6.3 or Later;Release - 1.0.7</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <!-- AssemblyName is set to FsLocalizationPlugin on purpose, renamed after build -->
    <AssemblyName>FsLocalizationPlugin</AssemblyName>
    <AssemblyTitle>FlammenwerferPlugin</AssemblyTitle>
    <PackageId>FrostyFlammenwerferPlugin</PackageId>
    <PackageId>FrostyFlammenwerferPlugin</PackageId>
    <Product>Frosty Flammenwerfer Plugin</Product>
    <Title>Frosty Flammenwerfer Plugin</Title>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <Version>0.4.1</Version>
    <FileVersion>0.4.1</FileVersion>
    <AssemblyVersion>0.4.1</AssemblyVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>shoushou1106</Authors>
    <RepositoryUrl>https://github.com/shoushou1106/FrostyFlammenwerferPlugin/</RepositoryUrl>
    <PackageProjectUrl>https://github.com/shoushou1106/FrostyFlammenwerferPlugin/</PackageProjectUrl>
    <Copyright>GPL-3.0</Copyright>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug - 1.0.7|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <EmbedAllSources>true</EmbedAllSources>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <OutputPath>bin\DeveloperDebug\1.0.7\</OutputPath>
    <DefineConstants>DEBUG;TRACE;FROSTY_DEVELOPER;FROSTY_107</DefineConstants>
    <IsDebug>true</IsDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug - 1.0.6.3 or Later|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <EmbedAllSources>true</EmbedAllSources>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <OutputPath>bin\DeveloperDebug\1.0.6.3orLater\</OutputPath>
    <DefineConstants>DEBUG;TRACE;FROSTY_DEVELOPER;FROSTY_1063_LATER</DefineConstants>
    <IsDebug>true</IsDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug - 1.0.6.2 or Earlier|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <EmbedAllSources>true</EmbedAllSources>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <OutputPath>bin\DeveloperDebug\1.0.6.2orEarlier\</OutputPath>
    <DefineConstants>DEBUG;TRACE;FROSTY_DEVELOPER;FROSTY_1062_EARLIER</DefineConstants>
    <IsDebug>true</IsDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - 1.0.7|x64'">
    <OutputPath>bin\ReleaseFinal\1.0.7\</OutputPath>
    <DefineConstants>TRACE;FROSTY_107</DefineConstants>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <IsDebug>false</IsDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - 1.0.6.3 or Later|x64'">
    <OutputPath>bin\ReleaseFinal\1.0.6.3orLater\</OutputPath>
    <DefineConstants>TRACE;FROSTY_1063_LATER</DefineConstants>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <IsDebug>false</IsDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - 1.0.6.2 or Earlier|x64'">
    <OutputPath>bin\ReleaseFinal\1.0.6.2orEarlier\</OutputPath>
    <DefineConstants>TRACE;FROSTY_1062_EARLIER</DefineConstants>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <IsDebug>false</IsDebug>
  </PropertyGroup>

  <!-- Integrated Workflow Detection -->
  <PropertyGroup>
    <IsIntegratedWorkflow>false</IsIntegratedWorkflow>
    <IsIntegratedWorkflow Condition="Exists('..\..\Plugins\') And Exists('..\..\FrostyPlugin\FrostyCore.csproj')">true</IsIntegratedWorkflow>
    <!-- Separate Workflow fallback -->
    <FrostyProjPath>..\FrostyToolsuite</FrostyProjPath>
    <!-- Integrated Workflow -->
    <FrostyProjPath Condition="$(IsIntegratedWorkflow)">..\..</FrostyProjPath>
  </PropertyGroup>
 
  <Target Name="CopyPluginIntegratedDebug" AfterTargets="PostBuildEvent" Condition="$(IsIntegratedWorkflow) And $(IsDebug)">
    <!-- Not renaming for debug -->
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(FrostyProjPath)\FrostyEditor\bin\Developer\Debug\Plugins\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(FrostyProjPath)\FrostyModManager\FrostyModManager\bin\Developer\Debug\Plugins\" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="CopyPluginIntegratedRelease" AfterTargets="PostBuildEvent" Condition="$(IsIntegratedWorkflow) And !$(IsDebug)">
    <!-- Rename for end-user experience -->
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(FrostyProjPath)\FrostyEditor\bin\Release\Final\Plugins\FlammenwerferPlugin.dll" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(FrostyProjPath)\FrostyModManager\bin\Release\Final\Plugins\FlammenwerferPlugin.dll" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="CopyPluginSeparateDebug" AfterTargets="PostBuildEvent" Condition="!$(IsIntegratedWorkflow) And $(IsDebug)">
    <!-- Not renaming for debug -->
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(FrostyProjPath)\FrostyEditor\bin\Developer\Debug\Plugins\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(FrostyProjPath)\FrostyModManager\bin\Developer\Debug\Plugins\" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="CopyPluginSeparateRelease" AfterTargets="PostBuildEvent" Condition="!$(IsIntegratedWorkflow) And !$(IsDebug)">
    <!-- Rename for end-user experience -->
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(FrostyProjPath)\FrostyEditor\bin\Release\Final\Plugins\FlammenwerferPlugin.dll" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(FrostyProjPath)\FrostyModManager\bin\Release\Final\Plugins\FlammenwerferPlugin.dll" SkipUnchangedFiles="true" />
  </Target>
  
  <ItemGroup>
    <Resource Include="Images\block_32dp_FFFFFF_FILL1_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\cancel_32dp_EA3323_FILL1_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\check_circle_32dp_75FB4C_FILL1_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\edit_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\error_32dp_FFFF55_FILL1_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\find_replace_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\frame_bug_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\handyman_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\label_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\quick_reference_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz40.png" />
    <Resource Include="Images\quick_reference_all_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz40.png" />
    <Resource Include="Images\shuffle_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
    <Resource Include="Images\tag_32dp_FFFFFF_FILL0_wght600_GRAD-25_opsz24.png" />
  </ItemGroup>

  <ItemGroup>
    <!-- Same reference as FrostyCore, use Editor as hint path, Mod Manager won't crash -->
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(FrostyProjPath)\FrostyEditor\ThirdParty\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(FrostyProjPath)\FrostyControls\FrostyControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="$(FrostyProjPath)\FrostyHash\FrostyHash.vcxproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="$(FrostyProjPath)\FrostyPlugin\FrostyCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="$(FrostyProjPath)\FrostySdk\FrostySdk.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
