name: "Bug 反馈"
description: "创建反馈以帮助我们进步（中文模板）"
title: "[哪里] 发生了什么"
labels:
- "bug"
assignees: 
- "shoushou1106"
projects: "shoushou1106/3"
body:
- type: markdown
  attributes:
    value: "这是一个中文模板，但中文模板只是方便您使用的，描述时请使用英语。如果英语不好，可以用中文写，然后同时附上中文原文+AI 英语翻译（请务必使用靠谱的 AI，例如 Gemini、DeepSeek 等多语言支持较好的模型）"
- type: input
  id: env-os
  attributes:
    label: OS & Version
    description: "您的操作系统和版本"
    placeholder: "Windows 11 Pro 25H2 (26200.8875), Linux Debian 13.6.0, macOS 27"
  validations:
    required: true
- type: input
  id: env-frosty-provider
  attributes:
    label: Frosty - Provider (Blank = Official)
    description: "您的 Frosty 提供方，留空默认为官方（CadeEvs）"
    placeholder: "HarGabt (HarGabt/FrostyToolsuite)"
  validations:
    required: false
- type: input
  id: env-frosty-version
  attributes:
    label: Frosty - Version
    description: "您的 Frosty 版本，也可以是某个 commit 的链接"
    placeholder: "1.0.6.3, 1.0.7 (HarGabt's fork) v.26.01.10, Branch/Tag/SHA"
  validations:
    required: true
- type: checkboxes
  id: env-frosty-app
  attributes:
    label: Frosty - App
    description: "您使用的 Frosty 应用"
    options:
      - label: Editor（编辑器）
      - label: Mod Manager（模组管理器）
      - label: Other（其他）
  validations:
    required: true
- type: input
  id: env-flame-provider
  attributes:
    label: Flammenwerfer - Provider
    description: "您的喷火器插件提供方，留空默认为官方（shoushou1106）"
    placeholder: "您的 Repo (到 Repo 的链接), 您的 Action 快速生成 (到 Action 的链接)"
  validations:
    required: false
- type: input
  id: env-flame-version
  attributes:
    label: Flammenwerfer - Version
    description: "您的喷火器插件版本"
    placeholder: "0.4.0, 0.3.1, Branch/SHA(link here)"
  validations:
    required: true
- type: input
  id: describe
  attributes:
    label: Describe the bug
    description: "清晰、简洁的描述 Bug（必填）"
    placeholder: "示例：我的方便面里没有调料包"
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Reproduction steps
    description: "重现此行为的步骤（非必填）"
    placeholder: |
      1. 从柜子里拿出方便面
      2. 打开方便面
      3. 发现没有调料包
      ...
  validations:
    required: false
- type: textarea
  id: expectation
  attributes:
    label: Expected behavior
    description: "清晰、简洁的描述你期望发生的事情（必填）"
    placeholder: "方便面里应该有调料包才对"
  validations:
    required: true
- type: upload
  id: screenshots
  attributes:
    label: Upload files
    description: "添加屏幕截图或日志文件以帮助说明您的问题（非必填）"
  validations:
    required: false
- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: "补充有关问题的其他信息（非必填）"
    placeholder: "这个问题是偶发性的，方便面里有时候有调料包，但有时候没有。我在遇到这个问题的时候还发现我居然没有火腿肠可以加到方便面里。"
  validations:
    required: false
